### PR TITLE
Deduplication of relationships

### LINKED ISSUE #41: Manually deduplicate obvious duplicate relationships.
In our post-import database, there are a number of duplicate relationships (i.e. where there are 2 records in the link table that have identical ids for both linked Models). Example in screenshot below.

This is probably just a minor error in importing - I suspect I didn't fully clear out an old test import before re-running the final one. We should dedup.

CleanShot 2024-03-08 at 10 15 40

### PR DESCRIPTION
**Pull request by dave-mills**
Small PR - fixes #41. 

Adds a one-time command to deduplicate entries in the metrics_ relationship pivot tables. Run `php artisan app:remove-duplicate-link-table-entries` to deduplicate entries in metrics pivot tables. 

Also moved all our 'one-time' commands to a dedicated folder. 

### Notes (SQL queries to check)

Testing with metrics_collection_method: 

```

select
    count(id),
    metric_id,
    collection_method_id
from metric_collection_method
group by metric_id, collection_method_id
order by count(id) desc; -- 11,797 unique entries.

select count(id) from metric_collection_method; 
-- BEFORE running command: 12286 entries;
-- AFTER running command: 11797 entries;

```

Approach used doesn't keep pivot values from any duplicates, but there are no duplicated entries with different pivot values:

```
-- All the below show 0 entries except where indicated.

select * from metric_collection_method where relation_notes is not null; -- 0 entries.
select * from metric_dimension where relation_notes is not null;
select * from metric_farming_system where relation_notes is not null;
select * from metric_framework where relation_notes is not null;
    -- framework_id 1; metric_id 1 - only 1 entry.

select * from metric_geography where relation_notes is not null;
select * from metric_metric where relation_notes is not null;
select * from metric_metric_user where relation_notes is not null;
-- metric id 1; metric_user_id 1 - only 1 entry.

select * from metric_parent_child where relation_notes is not null;
select * from metric_property_options where relation_notes is not null;
select * from metric_scale where relation_notes is not null;
  -- 3 entries; scale_id = 2 is duplicated, but the relation_notes are identical. 

select * from metric_scale where metric_id = 1 and scale_id in (2,3,4);
select * from metric_sub_dimension where relation_notes is not null;
select * from metric_theme where relation_notes is not null;
select * from metric_tool where relation_notes is not null;
select * from metric_topic where relation_notes is not null;
select * from metric_unit where relation_notes is not null;
```

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I can see the objective of this PR. This is good.

I can run first three pivot tables successfully. It works well after running SQL for checking in backend database.

Just a few little questions:
1. Why do we need to handle scales pivot table twice?
2. Do we need to handle themes pivot table?
3. When I run all pivot tables, I got out of memory issue...

image

**Comment by dave-mills** [comment]
> 1. Why do we need to handle scales pivot table twice?
> 2. Do we need to handle themes pivot table?

We don't, and yes! Good spots - thanks.

> 3. When I run all pivot tables, I got out of memory issue...

My current memory limit locally is 2048M (I've set it very high so for one-offs like this I don't need to put time into optimising). 

My guess is that you could dramatically reduce the amount of memory being used by calling a separate Job for each metric - (making it multi-threaded, essentially). Then you do one at a time in different threads, and once each thread is complete it releases the memory it used. That's probably what I'd suggest if we were going to run this daily on the server, but I don't think we need to do that here.

**Comment by dan-tang-ssd** [comment]
> > 1. Why do we need to handle scales pivot table twice?
> > 2. Do we need to handle themes pivot table?
> 
> We don't, and yes! Good spots - thanks.

I got this error when running for themes pivot table. It looks like due to a missing column...?

image


 
> > 3. When I run all pivot tables, I got out of memory issue...
> 
> My current memory limit locally is 2048M (I've set it very high so for one-offs like this I don't need to put time into optimising).
> 
> My guess is that you could dramatically reduce the amount of memory being used by calling a separate Job for each metric - (making it multi-threaded, essentially). Then you do one at a time in different threads, and once each thread is complete it releases the memory it used. That's probably what I'd suggest if we were going to run this daily on the server, but I don't think we need to do that here.

Yes, I agree.

**Comment by dave-mills** [comment]
> I got this error when running for themes pivot table. It looks like due to a missing column...?

It looks to me like a mispelt column (`unreviewd_import`). I found the issue and fixed it.

(Note - I also accidentally left a change I made in AppServiceProvider, to make the default text areas bigger app-wide, thus the extra commit)

**Comment by dan-tang-ssd** [comment]
It works well now.
I changed to allocate 2048 MB to php, it can run all pivot tables successfully.

I think it is good to merge now.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
