### PR TITLE
Add Importers

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to add importers for tool evaluations csv file and metric evaluation csv file.

This PR is not ready for review yet. It serves as a progress update.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
The importer program can now handle entities only. I will revise it to handle relationship soon.

---

I viewed CSV file "tool_evaluations_18Oct23.csv".

I found below columns that require to insert or update records for entities:
 - F: tool_name
 - K: developer
 - X: dimensions
 - AG: named_framework
 - AP: scale_measure

Question: Is there any other entity columns need to be handled?

---

Below two columns are for relationships:
 - H: rayyan_ref, to create relationship between metric and tool in link table "metric_tool"
 - AP: scale_measure, to create relationship between metric and scale in link table "metric_scale"

Question: Is there any other relationship columns need to be handled?

**Comment by dan-tang-ssd** [comment]
I have finished the importer program for tool evaluation csv file. 
Maybe it is a good time to take a look before working on metric evalution csv file.

---

Testing procedure

1. Import Dave's MySQL dump file into local db
2. Pull latest code from this branch
3. Run migration files
4. Run seeder file for sustainable development goals (SDGs), SdgsSeeder.php
5. Copy tool evaluation csv file to "storage/csv/tool_evaluations_18Oct23.csv"
6. execute command to run importer for tool evaluation csv file
`php artisan app:import-csv-tool-evaluations`

---

Tool evaluation csv file handling

There are 4 types of columns:
1. Meta data, column B "include" to determine import a row or not
2. Add new column to existing tools table
3. Add column data to existing entity table, add link table if it is not existed
4. Add column data to new entity table, new link table

Most 3 and 4 tasks are done by a generalised function.

Excel file for my study FYI:
[tool_evaluations_18Oct23_Study.xlsx](https://github.com/stats4sd/tpp-metrics-library/files/14375146/tool_evaluations_18Oct23_Study.xlsx)


Some special handlings done for below columns:
 - tool_id and tool_name, to create new tools record (I removed the existing tool record by re-creating tools table, this is to keep the original tool_id in csv file)
 - rayyan_ref, to create placeholder records in references table
 - dimensions and named_framework, comma symbol is used as comma instead of delimiter
 - framing_definition, it looks like the definition for Conceptual_framing. I found framing model by Conceptual_framing, then add framing_definition to column framing.definition.
 - sgd, it looks like a typo as it should be sdg (stands for sustainable development goals). I added SDG records by seeder file.
 - scale_measure and scale_report, I added entity records to scales table only. I cannot add records to link table metric_scale because I do not have the relationship for metric and scale at this moment.

---

Approach for adding relationship:

We discussed two different approaches for handling relationship:
1. metric -> reference -> e.g. dimension
2. metric -> dimension

Option 2 is preferred because it is more direct and metric is the core object in this application.

To achieve option 2, we may need to handle two csv files in below sequence:
1. Import tool evulation csv file, to add records to different entities and link tables
2. Import metric evaluation csv file, to add relationship between metric and tool
   - At this point, we should have imported all metrics and tool records.
3. Import tool evaluation csv file again, to add relationship between metric and different entities

**Comment by dan-tang-ssd** [comment]
I added a command to create relationship between metric and entities.

I did a checking in table referencables, there are six referencable_types:
1. App\Models\CollectionMethod
2. App\Models\Dimension
3. App\Models\Geography
4. App\Models\Scale
5. App\Models\Tool
6. App\Models\Metric

I handled the first five. For the sixth one Metric, I did not handle it because it potential becomes a self reference.

---

There are some other link tables in database, e.g. 
metric_farming_system
metric_framework
metric_metric
metric_metric_user
metric_sub_dimension
metric_theme
metric_topic
metric_unit
metric_user_tool

I guess we may need to add records in corresponding link tables when we have their records in table referencables.

**Comment by dan-tang-ssd** [comment]
I was running the new command for all metrics in my local env.
It hit an out of memory error as I allocated 512 MB to PHP in php.ini.
Just a quick note here for reference.

Perhaps I should allocate more memory to PHP, e.g. 2048 MB.
Um... but... why the used memory keep accumulating and not released for re-use...?

image

**Review by dave-mills — APPROVED** [review]

**Pull request merged**
